server:
  port: 8080
spring:
  application:
    name: user-service
    port: 8080
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-service:8082
          jwk-set-uri: http://auth-service:8082/oauth2/jwks
      client:
        registration:
          my-oidc-client:
            provider: my-oidc-provider
            client-id: user-client
            client-secret: KLJIHUGJKKLIJHGHGGF
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: openid
        provider:
          my-oidc-provider:
            issuer-uri: http://auth-service:8082
            authorization-uri: http://auth-service:8082/oauth2/authorize
            token-uri: http://auth-service:8082/oauth2/token
            user-info-uri: http://auth-service:8082/oauth2/userinfo
            user-name-attribute: sub
            jwk-set-uri: http://auth-service:8082/oauth2/jwks
  cache:
    type: redis
  data:
    redis:
      host: redis
      port: 6379
      ttl: 5
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/user_service
    username: admin
    password: admin
  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:db/changelog-master.yaml
    default-schema: public
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true

springdoc:
  swagger-ui:
    csrf:
      enabled: true
    oauth:
      client-id: user-client
      use-pkce-with-authorization-code-grant: false
    oauth2-redirect-url: http://user-service:8080/swagger-ui/oauth2-redirect.html
  oAuthFlow:
    authorizationUrl: http://auth-service:8082/oauth2/authorize
    tokenUrl: http://auth-service:8082/oauth2/token
    scopes: openid
swagger-server: http://user-service:8080/