server:
  port: ${PORT}
spring:
  profiles:
    default: ${SPRING_PROFILE}
  application:
    name: user-service
    port: ${PORT}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_ISSUER}
          jwk-set-uri: ${AUTH_JWKS}
  cache:
    type: redis
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
      ttl: 5
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:5432/user_service
    username: admin
    password: admin
  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:db/changelog-master.yaml
    default-schema: public
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true

springdoc:
  swagger-ui:
    csrf:
      enabled: true
swagger-server: http://user-service:8080/

otel:
  traces:
    sampler: always_on
  exporter:
    otlp:
      traces:
        endpoint: http://otel-collector.monitoring.svc.cluster.local:4317
        protocol: grpc
      metrics:
        endpoint: http://otel-collector.monitoring.svc.cluster.local:4317
        protocol: grpc
      logs:
        endpoint: http://otel-collector.monitoring.svc.cluster.local:4317
        protocol: grpc